### ISSUE TITLE
请问一下我用同样的unity版本打不开场景,能帮忙解释下吗？谢谢啦

### ISSUE THREAD

**Issue by fengyuzheng2020** [jzyong/ugk-server#2]
Failed to load '/Users/fengyuzheng/unity_project/ugk-server/ugk-game/game-galactic-kittens/galactic-kittens-game/Assets/Scenes/Game/GalacticKittens/GalacticKittensGamePlay.unity'. File may be corrupted or was serialized with a newer version of Unity.

**Comment by jzyong** [comment]
需要安装git-lfs，用了这个进行版本控制 https://git-lfs.com/
